CREATE TABLE MOVIMENTACOES( 
	MOV_CODIGO SERIAL PRIMARY KEY,
	 MOV_DATA TIMESTAMP,
	 MOV_DESCRICAO VARCHAR(50),
	 MOV_CATEGORIA VARCHAR(30),
	 MOV_ENTRADA NUMERIC(12,4),
	 MOV_SAIDA NUMERIC(12,4),
	 MOV_SALDO_ANTERIOR NUMERIC(12,4)
);