CREATE TABLE CATEGORIA( 
	 id SERIAL PRIMARY KEY,
	 name VARCHAR(30)
);

CREATE TABLE MOVIMENTACOES( 
	 id SERIAL PRIMARY KEY,
	 data DATE,
	 descricao VARCHAR(50),
	 tipo VARCHAR(30),
	 categoria_id int REFERENCES CATEGORIA(id),
	 valor NUMERIC(9,2)
);